# Data Cleaning

In [6]:
import os
from pathlib import Path
import sys


PROJECT_ROOT = Path(os.getcwd()).parent 

sys.path.append(str(PROJECT_ROOT))

In [7]:
%store -r df_final
df_final

,CERT,year,ZIP,STALP,NAME,CITY,HEAT_DAYS,TMAX_AVG,HEAT_SHOCK_DUMMY,ASSET,...,CAR,ROA_annual,NIM_annual,NPL_ratio,ROA_sd3,Z_score,ln_Zscore,HEAT_DAYS_LAG1,HEAT_DAYS_LAG2,TMAX_AVG_LAG1
0,2413,2010,78130,TX,First State Bank,New Braunfels,12,25.279178,1,265803.00,...,9.737004,1.478374,7242.000000,0.549373,0.136437,82.201460,4.409173,NaN,NaN,NaN
1,2413,2011,78130,TX,First State Bank,New Braunfels,82,27.663014,1,269938.25,...,10.410714,1.593003,7649.250000,1.078487,0.198613,60.437457,4.101609,12.0,NaN,25.279178
2,2413,2012,78130,TX,First State Bank,New Braunfels,30,27.043716,1,262885.00,...,10.370187,1.308460,5956.666667,0.456600,0.143164,81.574857,4.401521,82.0,12.0,27.663014
3,2429,2010,23487,VA,Farmers Bank,Windsor,64,20.566849,1,447099.75,...,8.036014,-1.570221,8395.500000,2.315535,1.160062,5.573657,1.718051,NaN,NaN,NaN
4,2429,2011,23487,VA,Farmers Bank,Windsor,48,21.340548,1,443244.25,...,8.452338,0.454322,8196.250000,1.787784,1.167621,7.628034,2.031830,64.0,NaN,20.566849
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2649,90234,2020,1945,MA,Marblehead Bank,Marblehead,48,15.070219,1,241358.50,...,7.965537,0.223696,4561.000000,0.302973,0.063135,129.708336,4.865288,41.0,45.0,13.743836
2650,90234,2021,1945,MA,Marblehead Bank,Marblehead,40,14.713425,1,285435.00,...,6.745143,0.238244,4523.250000,0.052727,0.055040,126.875108,4.843203,48.0,41.0,15.070219
2651,90234,2022,1945,MA,Marblehead Bank,Marblehead,51,15.088493,1,287777.25,...,6.807348,0.112663,4918.500000,0.036313,0.068691,100.740181,4.612545,40.0,48.0,14.713425
2652,90234,2023,1945,MA,Marblehead Bank,Marblehead,37,14.861918,1,262655.50,...,8.357716,0.592921,6248.500000,0.102987,0.249070,35.936151,3.581744,51.0,40.0,15.088493
2653,90234,2024,1945,MA,Marblehead Bank,Marblehead,46,14.926503,1,260212.75,...,9.149244,0.381736,5946.000000,0.089830,0.240710,39.595176,3.678707,37.0,51.0,14.861918

### Preprocessing

In [8]:
# Missing value
df_final.isnull().sum()

CERT                  0
year                  0
ZIP                   0
STALP                 0
NAME                  0
CITY                  0
HEAT_DAYS             0
TMAX_AVG              0
HEAT_SHOCK_DUMMY      0
ASSET                 0
EQTOT                 0
LNLSNET               0
NIM                   0
ROA                   0
RBCT1J                0
NAASSET               0
P9ASSET               0
P3ASSET               0
NONII                 0
NONIX                 0
latitude              0
longitude             0
SIZE                  0
CAR_ratio             0
CAR                   0
ROA_annual            0
NIM_annual            0
NPL_ratio             0
ROA_sd3               0
Z_score               0
ln_Zscore             0
HEAT_DAYS_LAG1      213
HEAT_DAYS_LAG2      426
TMAX_AVG_LAG1       213
dtype: int64

In [ ]:
# Drop missing value
core_features = [
    'CERT', 'year', 'ZIP',            # Định danh
    'NPL_ratio',                      # Biến Y chính
    'HEAT_DAYS', 'TMAX_AVG',          # Biến X chính
    'SIZE', 'CAR', 'NIM'              # Các biến kiểm soát 
]

df_clean_panel = df_final.dropna(subset=core_features)

In [14]:
# Winsorize 1%-99%
vars_to_winsorize = ['SIZE', 'ROA_annual', 'CAR', 'NIM', 'NPL_ratio', 'Z_score']
from src.preprocessing.winsorize import apply_winsorization

df_winsorized = apply_winsorization(
    df=df_clean_panel,
    columns_to_winsorize=vars_to_winsorize,
    limits=[0.01, 0.01]
)

Đã xử lý Winsorize thành công cho cột: SIZE
Đã xử lý Winsorize thành công cho cột: ROA_annual
Đã xử lý Winsorize thành công cho cột: CAR
Đã xử lý Winsorize thành công cho cột: NIM
Đã xử lý Winsorize thành công cho cột: NPL_ratio
Đã xử lý Winsorize thành công cho cột: Z_score

In [15]:
df_winsorized

,CERT,year,ZIP,STALP,NAME,CITY,HEAT_DAYS,TMAX_AVG,HEAT_SHOCK_DUMMY,ASSET,...,CAR,ROA_annual,NIM_annual,NPL_ratio,ROA_sd3,Z_score,ln_Zscore,HEAT_DAYS_LAG1,HEAT_DAYS_LAG2,TMAX_AVG_LAG1
0,2413,2010,78130,TX,First State Bank,New Braunfels,12,25.279178,1,265803.00,...,9.737004,1.478374,7242.000000,0.549373,0.136437,82.201460,4.409173,NaN,NaN,NaN
1,2413,2011,78130,TX,First State Bank,New Braunfels,82,27.663014,1,269938.25,...,10.410714,1.593003,7649.250000,1.078487,0.198613,60.437457,4.101609,12.0,NaN,25.279178
2,2413,2012,78130,TX,First State Bank,New Braunfels,30,27.043716,1,262885.00,...,10.370187,1.308460,5956.666667,0.456600,0.143164,81.574857,4.401521,82.0,12.0,27.663014
3,2429,2010,23487,VA,Farmers Bank,Windsor,64,20.566849,1,447099.75,...,8.036014,-1.309238,8395.500000,2.315535,1.160062,5.762183,1.718051,NaN,NaN,NaN
4,2429,2011,23487,VA,Farmers Bank,Windsor,48,21.340548,1,443244.25,...,8.452338,0.454322,8196.250000,1.787784,1.167621,7.628034,2.031830,64.0,NaN,20.566849
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2649,90234,2020,1945,MA,Marblehead Bank,Marblehead,48,15.070219,1,241358.50,...,7.965537,0.223696,4561.000000,0.302973,0.063135,129.708336,4.865288,41.0,45.0,13.743836
2650,90234,2021,1945,MA,Marblehead Bank,Marblehead,40,14.713425,1,285435.00,...,6.745143,0.238244,4523.250000,0.052727,0.055040,126.875108,4.843203,48.0,41.0,15.070219
2651,90234,2022,1945,MA,Marblehead Bank,Marblehead,51,15.088493,1,287777.25,...,6.807348,0.112663,4918.500000,0.036313,0.068691,100.740181,4.612545,40.0,48.0,14.713425
2652,90234,2023,1945,MA,Marblehead Bank,Marblehead,37,14.861918,1,262655.50,...,8.357716,0.592921,6248.500000,0.102987,0.249070,35.936151,3.581744,51.0,40.0,15.088493
2653,90234,2024,1945,MA,Marblehead Bank,Marblehead,46,14.926503,1,260212.75,...,9.149244,0.381736,5946.000000,0.089830,0.240710,39.595176,3.678707,37.0,51.0,14.861918